// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_votacion.Data;

namespace Sistema_de_votacion.Migrations
{
    [DbContext(typeof(ElectionDBContext))]
    partial class ElectionDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sistema_de_votacion.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("PoliticPartyId");

                    b.Property<int>("PositionId");

                    b.Property<string>("ProfilePhothoPath")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("PoliticPartyId");

                    b.HasIndex("PositionId");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnName("DNI")
                        .HasMaxLength(13);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Citizen");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Election");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.ElectionCadidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidateId");

                    b.Property<int>("ElectionId");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectionId");

                    b.ToTable("ElectionCadidate");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.ElectionCitizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CitizenId");

                    b.Property<int>("ElectionId");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ElectionId");

                    b.ToTable("ElectionCitizen");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.ElectionPoliticParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ElectionId");

                    b.Property<int>("PoliticPartyId");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("PoliticPartyId");

                    b.ToTable("ElectionPoliticParty");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.ElectionPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ElectionId");

                    b.Property<int>("PositionId");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("PositionId");

                    b.ToTable("ElectionPosition");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.PoliticParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PartyLogoPath")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("PoliticParty");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.Candidate", b =>
                {
                    b.HasOne("Sistema_de_votacion.Models.PoliticParty", "PoliticParty")
                        .WithMany("Candidate")
                        .HasForeignKey("PoliticPartyId")
                        .HasConstraintName("FK_Candidate_PoliticParty");

                    b.HasOne("Sistema_de_votacion.Models.Position", "Position")
                        .WithMany("Candidate")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("FK_Candidate_Position");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.ElectionCadidate", b =>
                {
                    b.HasOne("Sistema_de_votacion.Models.Candidate", "Candidate")
                        .WithMany("ElectionCadidate")
                        .HasForeignKey("CandidateId")
                        .HasConstraintName("FK_ElectionCandidate_Candidate");

                    b.HasOne("Sistema_de_votacion.Models.Election", "Election")
                        .WithMany("ElectionCadidate")
                        .HasForeignKey("ElectionId")
                        .HasConstraintName("FK_ElectionCandidate_Election");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.ElectionCitizen", b =>
                {
                    b.HasOne("Sistema_de_votacion.Models.Citizen", "Citizen")
                        .WithMany("ElectionCitizen")
                        .HasForeignKey("CitizenId")
                        .HasConstraintName("FK_ElectionCitizen_Citizen");

                    b.HasOne("Sistema_de_votacion.Models.Election", "Election")
                        .WithMany("ElectionCitizen")
                        .HasForeignKey("ElectionId")
                        .HasConstraintName("FK_ElectionCitizen_Election");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.ElectionPoliticParty", b =>
                {
                    b.HasOne("Sistema_de_votacion.Models.Election", "Election")
                        .WithMany("ElectionPoliticParty")
                        .HasForeignKey("ElectionId")
                        .HasConstraintName("FK_ElectionPoliticParty_Election");

                    b.HasOne("Sistema_de_votacion.Models.PoliticParty", "PoliticParty")
                        .WithMany("ElectionPoliticParty")
                        .HasForeignKey("PoliticPartyId")
                        .HasConstraintName("FK_ElectionPoliticParty_PoliticParty");
                });

            modelBuilder.Entity("Sistema_de_votacion.Models.ElectionPosition", b =>
                {
                    b.HasOne("Sistema_de_votacion.Models.Election", "Election")
                        .WithMany("ElectionPosition")
                        .HasForeignKey("ElectionId")
                        .HasConstraintName("FK_ElectionPosition_Election");

                    b.HasOne("Sistema_de_votacion.Models.Position", "Position")
                        .WithMany("ElectionPosition")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("FK_ElectionPosition_Position");
                });
#pragma warning restore 612, 618
        }
    }
}
